### ISSUE TITLE
Turn google doc into issues

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/product-managment#1]
### Overview
We need to update the project board so that it is reflective of what we are actually working on

### Action Items
Convert Abi's word doc to issues

### Resources/Instructions
[Abi/Bonnie Actions](https://docs.google.com/document/d/1t3HN4e3n9vb95utAd4s_9WbIDU86YoLaWVvMV_PhyuE/edit)

**Comment by abi-a** [comment]
This is resolved, all the actions in the document are completed

**Comment by ExperimentsInHonesty** [comment]
Thanks!
