### ISSUE TITLE
Document cleanup

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/product-managment#2]
### Overview
Create a place for prior drafts and make sure documents have the same name plus some kind of draft designation. But not in the delivery folder.

### Action Items
- [x] Make sure this document ends up in the drafts folder 
   - Notes for what we ended up sending to IJ 
      - https://drive.google.com/file/d/1lvlfZY3XQV1oscaWoPvTsRbMLSnmPrMZ/view
- [x] Delete this document.  There is already an issue with this info in it
   - Agenda for first meeting
     - https://docs.google.com/document/d/1O3Yyk-5uO0agjxPk38aBqi_btksxwrqQ0S9D2blAeQI/edit

### Resources/Instructions
[Racial Justice Google Drive](https://drive.google.com/drive/u/1/folders/1cTgo8PMgdz809d0kaDtaZ_qSvN4VpbCZ)
[Abi/Bonnie Google Drive](https://drive.google.com/drive/u/0/folders/147nzYyiTXFf5npOz9eoSAiINxZ4KWS9-)

**Comment by abi-a** [comment]
This is completed

**Comment by ExperimentsInHonesty** [comment]
Great.  Thanks!
